name: Back-end CI/CD/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pipeline:
    name: Build, publish and rollout
    runs-on: ubuntu-latest

    steps:
      - name: Clone source code
        uses: actions/checkout@v4

      # - name: Set up JDK 17
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: 'corretto'
      #     java-version: '17'
      #     cache: 'maven'
      # - name: Maven build
      #   run: mvn -B package --file pom.xml

      - name: AWS ECR login
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_APP_ECR_REPO }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_SECRET_KEY: ${{ secrets.AWS_ACCESS_SECRET_KEY }}

      - name: Docker image
        run: |
          docker build -t ${{ secrets.AWS_APP_ECR_REPO }}:latest

      - name: 'Pushes image to ECR'
        run: |
          docker push ${{ secrets.AWS_APP_ECR_REPO }}:latest